on: [push, pull_request]
name: test
jobs:
    test:
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Build the docker-compose stack
                run: docker-compose up -d
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
            -   name: Install dependencies
                run: composer install --prefer-dist --no-interaction
            -   name: Setup test db
                run: php bin/console doctrine:database:create --env=test --no-interaction && php bin/console doctrine:migrations:migrate --env=test --no-interaction

